//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompupartsServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://compuparts.notld/")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuantityInStockField;
        
        private double PriceField;
        
        private System.DateTime DeliveryDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuantityInStock {
            get {
                return this.QuantityInStockField;
            }
            set {
                if ((this.QuantityInStockField.Equals(value) != true)) {
                    this.QuantityInStockField = value;
                    this.RaisePropertyChanged("QuantityInStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((this.DeliveryDateField.Equals(value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://compuparts.notld/", ConfigurationName="CompupartsServiceProxy.CompupartsSoap")]
    public interface CompupartsSoap {
        
        // CODEGEN: Generating message contract since element name GetAllInformationResult from namespace http://compuparts.notld/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://compuparts.notld/GetAllInformation", ReplyAction="*")]
        CompupartsServiceProxy.GetAllInformationResponse GetAllInformation(CompupartsServiceProxy.GetAllInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://compuparts.notld/GetStock", ReplyAction="*")]
        int GetStock(int prod_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://compuparts.notld/GetPrice", ReplyAction="*")]
        double GetPrice(int prod_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://compuparts.notld/GetDeliveryDate", ReplyAction="*")]
        System.DateTime GetDeliveryDate(int prod_id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllInformation", Namespace="http://compuparts.notld/", Order=0)]
        public CompupartsServiceProxy.GetAllInformationRequestBody Body;
        
        public GetAllInformationRequest() {
        }
        
        public GetAllInformationRequest(CompupartsServiceProxy.GetAllInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://compuparts.notld/")]
    public partial class GetAllInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int prod_id;
        
        public GetAllInformationRequestBody() {
        }
        
        public GetAllInformationRequestBody(int prod_id) {
            this.prod_id = prod_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllInformationResponse", Namespace="http://compuparts.notld/", Order=0)]
        public CompupartsServiceProxy.GetAllInformationResponseBody Body;
        
        public GetAllInformationResponse() {
        }
        
        public GetAllInformationResponse(CompupartsServiceProxy.GetAllInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://compuparts.notld/")]
    public partial class GetAllInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompupartsServiceProxy.ServiceResponse GetAllInformationResult;
        
        public GetAllInformationResponseBody() {
        }
        
        public GetAllInformationResponseBody(CompupartsServiceProxy.ServiceResponse GetAllInformationResult) {
            this.GetAllInformationResult = GetAllInformationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompupartsSoapChannel : CompupartsServiceProxy.CompupartsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompupartsSoapClient : System.ServiceModel.ClientBase<CompupartsServiceProxy.CompupartsSoap>, CompupartsServiceProxy.CompupartsSoap {
        
        public CompupartsSoapClient() {
        }
        
        public CompupartsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompupartsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompupartsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompupartsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompupartsServiceProxy.GetAllInformationResponse CompupartsServiceProxy.CompupartsSoap.GetAllInformation(CompupartsServiceProxy.GetAllInformationRequest request) {
            return base.Channel.GetAllInformation(request);
        }
        
        public CompupartsServiceProxy.ServiceResponse GetAllInformation(int prod_id) {
            CompupartsServiceProxy.GetAllInformationRequest inValue = new CompupartsServiceProxy.GetAllInformationRequest();
            inValue.Body = new CompupartsServiceProxy.GetAllInformationRequestBody();
            inValue.Body.prod_id = prod_id;
            CompupartsServiceProxy.GetAllInformationResponse retVal = ((CompupartsServiceProxy.CompupartsSoap)(this)).GetAllInformation(inValue);
            return retVal.Body.GetAllInformationResult;
        }
        
        public int GetStock(int prod_id) {
            return base.Channel.GetStock(prod_id);
        }
        
        public double GetPrice(int prod_id) {
            return base.Channel.GetPrice(prod_id);
        }
        
        public System.DateTime GetDeliveryDate(int prod_id) {
            return base.Channel.GetDeliveryDate(prod_id);
        }
    }
}
